# Generated by Django 4.1 on 2022-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("ft", "Full Time"), ("pt", "Part Time")],
                default="ft",
                max_length=10,
            ),
        ),
    ]
