# Generated by Django 4.1 on 2022-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="career_level",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("entry level", "Entry Level"),
                    ("junior", "Junior"),
                    ("senior", "Senior"),
                    ("manager", "Manager"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job", name="experiance", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="job_requirment",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="job", name="vacancy", field=models.IntegerField(default=1),
        ),
    ]
