# Generated by Django 4.1 on 2022-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_job_career_level_job_experiance_job_job_requirment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(
                default=0,
                help_text="Enter number with zeros like 12000 not 12k",
                max_length=10,
            ),
        ),
    ]
