# Generated by Django 4.1 on 2022-08-27 13:40

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_job_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(
                default=0, help_text="Enter number with zeros like 12000 not 12k"
            ),
        ),
    ]
