# Generated by Django 4.1 on 2022-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_alter_job_image_alter_job_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                default="ft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
