# Generated by Django 4.1 on 2022-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_alter_job_job_type_alter_job_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
