# Generated by Django 4.1 on 2022-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
