# Generated by Django 4.1 on 2022-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_alter_job_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
